- include: "{{ ansible_os_family }}.yml"
  become: yes
  tags: kibana

- name: enable kibana service
  service:
    name: kibana
    state: started
    enabled: yes
  tags: kibana

- name: set elasticsearch instance to connect to
  lineinfile:
    dest: /opt/kibana/config/kibana.yml
    regexp: ^elasticsearch.url
    line: "elasticsearch.url: '{{kibana_elasticsearch_host}}'"
  notify:
    - restart kibana
  tags: kibana